"""Generate the embedded helper resource table; run after changing helper files."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
paths = [root/'scripts/jev_engine_gateway.py', root/'scripts/jev_model_adapters.py', root/'scripts/usage_ledger.py']
paths += sorted((root/'scripts/jev_adapters').rglob('*.py'))
paths += [root/'scripts/jev_adapters/LICENSE',root/'scripts/jev_adapters/UPSTREAM.json']
body = '// Generated by scripts/generate_jev_resources.py. Do not edit.\n'
body += 'pub const RESOURCES: &[(&str, &str)] = &[\n'
for path in paths:
    relative = path.relative_to(root/'scripts').as_posix()
    body += f'    ("{relative}", include_str!("../scripts/{relative}")),\n'
body += '];\n'
(root/'src/jev_resources.rs').write_text(body,encoding='utf-8')
