"""Refresh JevBench's full roster from a pinned public source (no runtime fetch)."""
import argparse, hashlib, json, pathlib, urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = 'fstandhartinger/model-market-comparison'
PATH = 'data/raw/benchmarks/jevbench/v1.5/jevbench-v1.5.4-results.json'

def fetch(path, revision):
    with urllib.request.urlopen(f'https://raw.githubusercontent.com/{SOURCE}/{revision}/{path}', timeout=45) as r:
        return r.read()

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--revision', required=True, help='Reviewed source commit SHA')
    args = parser.parse_args()
    raw = fetch(PATH, args.revision)
    data = json.loads(raw)
    links = json.loads(fetch('data/raw/benchmarks/jevbench/jev-system-links.json', args.revision))['links']
    engines = []
    for row in data['systems'] + data['not_measured']:
        adapter = row.get('adapter_id') or ''
        protocol = 'adapter'
        if 'TypeSafeAdapter' in adapter: protocol = 'systemone'
        elif 'SystemOneListAdapter' in adapter: protocol = 'systemone-list'
        elif 'OpenAICompatAdapter' in adapter: protocol = 'openai'
        elif 'Djev' in adapter or row['key'] == 'djev-thinking': protocol = 'djev'
        elif 'RemoteInproc' in adapter: protocol = 'run'
        elif 'ClassifierDev' in adapter: protocol = 'classifier-dev'
        source = row.get('repo') or links.get(row['key'], {}).get('url') or f"https://www.benchmarkheaven.com/jev-models/{row['key']}"
        engines.append(dict(id=row['key'], name=row['display'], source=source,
                            protocol=protocol, adapter=adapter, license=row.get('licence'),
                            open=row.get('open'), hardware=row.get('gpu') or row.get('endpoint_condition'),
                            support=row.get('support'), status=row.get('status'),
                            rank=row.get('rank'), model=None))
    # Deployment identifiers from public model cards/vendor docs, never the benchmark's private GPU URLs.
    models = {
        'jev-1.13.0':'jev-latest', 'djev':'djev', 'djev-thinking':'djev',
        'classifier-dev-fast':'fast', 'system-one-sg':'Qwen/Qwen3-8B',
        'open-alternative-jev':'Qwen/Qwen3.5-4B', 'cygnet':'cygnet',
        'winnow-12b':'EldanRing/Winnow-12B', 'jev-omni':'akhilaaa3/Jev-Omni',
        'hopper':'HopitAI/hopper', 'gliner2':'fastino/gliner2.5-base-v1',
        'gliner2-large':'fastino/gliner2-large-v1', 'gliner2.5-multi':'fastino/gliner2.5-multi-v1',
        'gliner2.5-small':'fastino/gliner2.5-small-v1', 'laya':'convaiinnovations/laya',
        'open-jev-deberta-v3-large':'com-kotobalabs/open-jev-deberta-v3-large',
        'certo':'altslate/certo-decision-model',
        'qwen3-reranker-4b':'Qwen/Qwen3-Reranker-4B', 'zerank-2':'zeroentropy/zerank-2-reranker',
        'bge-reranker-v2-m3':'BAAI/bge-reranker-v2-m3',
        'gte-reranker-modernbert-base':'Alibaba-NLP/gte-reranker-modernbert-base',
        'mxbai-rerank-base-v2':'mixedbread-ai/mxbai-rerank-base-v2',
    }
    for engine in engines:
        engine['model'] = models.get(engine['id'])
        if engine['model'] is None and engine['source'].startswith('https://huggingface.co/'):
            pieces = engine['source'].removeprefix('https://huggingface.co/').split('/')
            engine['model'] = '/'.join(pieces[:2])
    deployments=json.loads((ROOT/'scripts/jev-deployments.json').read_text(encoding='utf-8'))
    if set(deployments['engines']) != {e['id'] for e in engines}:
        raise ValueError('review new or removed roster entries before generating deployment support')
    for engine in engines:
        record=deployments['engines'][engine['id']]
        engine.update(record)
    # Reviewed engines newer than the pinned roster stay unranked until measured.
    supplements=json.loads((ROOT/'scripts/jev-supplements.json').read_text(encoding='utf-8'))
    roster={e['id'] for e in engines}
    for extra in supplements['engines']:
        if extra['id'] in roster:
            raise ValueError(f"{extra['id']} is now in the JevBench roster; drop its supplement")
        engines.append(extra)
    payload = dict(version=1, benchmark='JevBench v1.5.4', revision=args.revision,
                   source=f'https://github.com/{SOURCE}/blob/{args.revision}/{PATH}',
                   sha256=hashlib.sha256(raw).hexdigest(), engines=engines)
    (ROOT/'src/jev_catalog.json').write_text(json.dumps(payload, indent=2, ensure_ascii=False)+'\n', encoding='utf-8')
    doc='# Jev model compatibility\n\nGenerated by `scripts/sync_jev_catalog.py` from '+payload['source']+'. Deployment recipes reviewed '+deployments['reviewed']+'; '+str(len(supplements['engines']))+' newer engines from `scripts/jev-supplements.json` reviewed '+supplements['reviewed']+' (unranked until JevBench measures them).\n\nUse `nur jev models`, `nur jev info <id>`, then connect your endpoint or installed source runtime. A roster entry is not a claim of local hardware validation. Credentials are selected per engine.\n\n| Engine | Interface | Local adapter | Public source |\n|---|---|---|---|\n'
    for engine in engines:
        doc+=f"| `{engine['id']}` | {engine['protocol']} | {engine.get('local_adapter','source runtime / custom adapter')} | [source]({engine['source']}) |\n"
    (ROOT/'docs/jev-models.md').write_text(doc,encoding='utf-8')
    print(f'Wrote {len(engines)} engines from {args.revision}')

if __name__ == '__main__': main()
